variables:
  BRANCH_R: "master"
  
.test_template: &test_definition
  rules:
    - if: '$BRANCH_T'
      when: never
    - changes:
      - Run.py
      - default_variables.py
      - py_alf.py
      - .gitlab-ci.yml
  script:
    - apt-get update && apt-get install -y pylint3 python3-numpy git
    - if [ "$MACHINE" = "INTEL" ]; then . /opt/intel/oneapi/setvars.sh; fi
    - if [ $(command -v pylint3) ]; then linter='pylint3'; else linter='pylint'; fi
    - $linter -E Run.py default_variables.py py_alf.py
    - git clone https://git.physik.uni-wuerzburg.de/ALF/ALF.git
    - ./Run.py -R --alfdir ./ALF --machine $MACHINE --branch_R $BRANCH_R --ham_name_R Hubbard_Plain_Vanilla

.warn_template: &warn_definition
  allow_failure: true
  rules:
    - if: '$BRANCH_T'
      when: never
    - changes:
      - Run.py
      - default_variables.py
      - py_alf.py
      - .gitlab-ci.yml
  script:
    - apt-get update && apt-get install -y pylint3 python3-numpy
    - pylint Run.py default_variables.py py_alf.py
    
.test_branch_template: &test_branch_definition
  rules:
    - if: '$BRANCH_T'
      when: always
  script:
    - apt-get update && apt-get install -y python3-numpy git
    - export PYTHONPATH="$PWD:$PYTHONPATH"
    - if [ "$MACHINE" = "INTEL" ]; then . /opt/intel/oneapi/setvars.sh; fi
    - cd Scripts
    - ./test_branch.py --branch_R $BRANCH_R --branch_T $BRANCH_T --machine $MACHINE


Test_Stretch:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-blas-lapack-fftw-hdf5-scipy3
  variables:
    MACHINE: "GNU"
  <<: *test_definition

Test_Buster:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gfortran-blas-lapack-fftw-hdf5-scipy3
  variables:
    MACHINE: "GNU"
  <<: *test_definition

Test_Bullseye:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
  variables:
    MACHINE: "GNU"
  <<: *test_definition
  
Test-PGI:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-pgi-21-03
  variables:
    MACHINE: "PGI"
  <<: *test_definition

Test-Intel-21:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-intel-oneapi-ifort-python3
  variables:
    MACHINE: "INTEL"
  <<: *test_definition


Warn_Bullseye:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
  <<: *warn_definition


Test_branch_Stretch:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-blas-lapack-fftw-hdf5-scipy3
  variables:
    MACHINE: "GNU"
  <<: *test_branch_definition

Test_branch_Buster:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gfortran-blas-lapack-fftw-hdf5-scipy3
  variables:
    MACHINE: "GNU"
  <<: *test_branch_definition

Test_branch_Bullseye:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
  variables:
    MACHINE: "GNU"
  <<: *test_branch_definition
  
Test_branch-PGI:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-pgi-21-03
  variables:
    MACHINE: "PGI"
  <<: *test_branch_definition

Test_branch-Intel-21:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-intel-oneapi-ifort-python3
  variables:
    MACHINE: "INTEL"
  <<: *test_branch_definition
